apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: IdentityProvider
metadata:
  name: consolidated
spec:
  type: "gitlab"
  clusterName: "dscott"
  displayName: "gitlab"
  clusterAdmins:
    - dscott
  dedicatedAdmins:
    - jdoe
  gitlab:
    url: https://www.gitlab.com
    mappingMethod: "claim"
    secretRef:
      oauth: my-oauth-secret
      caCert: my-gitlab-cert
      api: my-api-credentials
  # github:
  # htpasswd:
