apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: autoscaling
spec:
  clusterName: "dscott-test"
  minimumNodesPerZone: 1
  maximumNodesPerZone: 2
  instanceType: m5.xlarge
