apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ocm-machine-pool-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MachinePool is the Schema for the machinepools API.
      displayName: Machine Pool
      kind: MachinePool
      name: machinepools.ocm.mobb.redhat.com
      version: v1alpha1
  description: Operator for controlling various OCM Objects using the Kubernetes operator
    pattern.
  displayName: OpenShift Cluster Manager Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ocm
  - rosa
  - redhat
  - machinepool
  - mobb
  links:
  - name: Ocm Machine Pool Operator
    url: https://ocm-machine-pool-operator.domain
  maintainers:
  - email: dscott@redhat.com
    name: Dustin Scott
  maturity: alpha
  provider:
    name: Managed OpenShift Black Belt
    url: https://github.com/rh-mobb/ocm-operator
  version: 0.0.0
