apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: machinepool-sample
spec:
  clusterName: "dscott"
  displayName: "test5"
  minimumNodesPerZone: 1
  maximumNodesPerZone: 1
  instanceType: m5.xlarge
  labels:
    this: that
  taints:
    - key: this
      value: that
      effect: NoSchedule
  aws:
    spotInstances:
      enabled: false
